set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g default-terminal "tmux-256color"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file /etc/tmux.conf \; display "reloaded"

set -g status-style bg=colour236,fg=colour252
set -g status-left "#[fg=colour114]#S "
set -g status-right "#[fg=colour244]#h  %H:%M"
